version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - mi_red
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=orlando
      - MONGO_INITDB_ROOT_PASSWORD=123
    volumes:
      - mongodb_data:/data/db

networks:
  mi_red:
    external: true

volumes:
  mongodb_data: